# Use the official Node.js Alpine image as the base image
FROM node:alpine

# Set the working directory in the Docker container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci --omit=dev

# Copy the rest of the backend code
COPY . .

EXPOSE 3000

# Start the application
CMD [ "npm", "run", "start:debug" ]
